In [6]:
import pandas as pd

In [9]:
df = pd.read_csv('../data/raw/wines_SPA.csv')
df.head()

,winery,wine,year,rating,num_reviews,country,region,price,type,body,acidity
0,Teso La Monja,Tinto,2013,4.9,58,Espana,Toro,995.00,Toro Red,5.0,3.0
1,Artadi,Vina El Pison,2018,4.9,31,Espana,Vino de Espana,313.50,Tempranillo,4.0,2.0
2,Vega Sicilia,Unico,2009,4.8,1793,Espana,Ribera del Duero,324.95,Ribera Del Duero Red,5.0,3.0
3,Vega Sicilia,Unico,1999,4.8,1705,Espana,Ribera del Duero,692.96,Ribera Del Duero Red,5.0,3.0
4,Vega Sicilia,Unico,1996,4.8,1309,Espana,Ribera del Duero,778.06,Ribera Del Duero Red,5.0,3.0

In [11]:
dicionario = pd.DataFrame([
    {
        "variavel": "winery",
        "descricao": "Vinícola do vinho",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "wine",
        "descricao": "Nome do vinho",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "year",
        "descricao": "Ano da safra do vinho",
        "tipo": "Quantitativa",
        "subtipo": "Contínua"
    },
    {
        "variavel": "rating",
        "descricao": "Avaliação do vinho (1-5)",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    {
        "variavel": "num_reviews",
        "descricao": "Número de avaliações",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    {
        "variavel": "country",
        "descricao": "País de origem",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "region",
        "descricao": "Região de origem",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "price",
        "descricao": "Preço do vinho em euros",
        "tipo": "Quantitativa",
        "subtipo": "Contínua"
    },
    {
        "variavel": "type",
        "descricao": "Tipo do vinho",
        "tipo": "Qualitativa",
        "subtipo": "Nominal"
    },
    {
        "variavel": "body",
        "descricao": "Classificação do corpo do vinho (1-5)",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    },
    {
        "variavel": "acidity",
        "descricao": "Classificação da acidez do vinho (1-5)",
        "tipo": "Quantitativa",
        "subtipo": "Discreta"
    }
])
dicionario.to_csv('../data/external/dictionary.csv', index=False)
dicionario

,variavel,descricao,tipo,subtipo
0,winery,Vinícola do vinho,Qualitativa,Nominal
1,wine,Nome do vinho,Qualitativa,Nominal
2,year,Ano da safra do vinho,Quantitativa,Contínua
3,rating,Avaliação do vinho (1-5),Quantitativa,Discreta
4,num_reviews,Número de avaliações,Quantitativa,Discreta
5,country,País de origem,Qualitativa,Nominal
6,region,Região de origem,Qualitativa,Nominal
7,price,Preço do vinho em euros,Quantitativa,Contínua
8,type,Tipo do vinho,Qualitativa,Nominal
9,body,Classificação do corpo do vinho (1-5),Quantitativa,Discreta
10,acidity,Classificação da acidez do vinho (1-5),Quantitativa,Discreta